### ISSUE TITLE
Looking for older (pre 2018-08-30) issues?

### ISSUE THREAD

**Issue by BluABK** [BluABK/sane-subfeed#1]
This project was previously self-hosted on GitLab. For older issues go here: https://git.blucoders.net/BluABK/sane-yt-subfeed/issues

**Comment by hawken93** [comment]
To be closed when all old issues are closed? :)

**Comment by BluABK** [comment]
> To be closed when all old issues are closed? :)

Yeah, pretty much. Locked it preemptively to avoid non-collaborator chatter.

**Comment by BluABK** [comment]
This is a test, ignore this comment.

**Comment by BluABK** [comment]
this is another test.

**Comment by BluABK** [comment]
and another test

**Comment by BluABK** [comment]
testing 2019-07-10

**Comment by BluABK** [comment]
testing integration
