### ISSUE TITLE
Bypass video download logic and simply paste video URL in command line of media player

### ISSUE THREAD

**Issue by lordkitsuna** [BluABK/sane-subfeed#13]
i.e.
click mpv https://youtu.be/12345

I didn't look at the code yet, and I'm fine with this being postponed until I can do it myself, but my guess tells me that some downloading logic would need to be bypassed based on media player settings..

say you have something like this in your settings:

media player command line="/path/to/mpv %s"

Playback method=(URL|file|pipe)

**Comment by lordkitsuna** [comment]
All download logic is easily bypassed by config options. And option to playback using url was added(untested_changes branch).

**Comment by BluABK** [comment]
Implemented fully in 1f034d4e366bb048ac83e024fbce90c6509c582a
